### ISSUE TITLE
Connect-SFApp: Unable to get account client ID for account in GCP east

### ISSUE THREAD

**Issue by yyx100** [Snowflake-Labs/sfsnowsightextensions#44]
Started in late October, Connect-SFApp is unable to authenticate with Snowflake accounts in GCP East 4 region.   The message plus error is:  
Connect-SFApp -Account  gq0xxxx.us-east4.gcp     -UserName dummy_tester

cmdlet Connect-SFApp at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
Password: ********
Account 'gq0xxxx' in region 'us-east4.gcp' is accessible at 'https://gq0xxxx.us-east4.gcp.snowflakecomputing.com' and served by application server 'https://apps-api.c1.us-east4.gcp.app.snowflake.com' in main application 'https://app.snowflake.com'
Connect-SFApp: Unable to get account client ID for account gq0xxxx

The test account above gq0xxxx is a simple brand new new account I created for troubleshooting this API issue only, and it is free of SSO, network policy configured to it.  I also confirmed this API still works for our AWS and GCP Central accounts.

**Comment by sfc-gh-mybarra** [comment]
@yyx100 the GCP East region is a new addition to the Snowflake regions. It is a strong possibility that this is a breaking change and cannot be remediated. The creator of this tool is no longer maintaining it. We have been doing our best to mitigate any issue that arise. However, snowsight extensions will eventually cease to function due to frequent changes to the Snowflake UI. We encourage you to speak to your Snowflake sales team to have them assist in our efforts to keep visibility on this matter. Together we can hopefully get snowsight extensions functionality added as an out of the box feature.

**Comment by yyx100** [comment]
ok.  thank.
